/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.spike.poker.hands

import org.amshove.kluent.`should be equal to`
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test

class PokerGameTest {
    @Nested
    inner class GivenTwoPlayers {

        @Nested
        inner class AndPokerRules {

            @Nested
            inner class WhenPokerRoundHasOneXAndOneY {

                @Test
                fun thenDoSomethingCool() {
                    "" `should be equal to` ""
                }
            }
        }
    }
}